version: "3.9"
services:
  db:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./_data/pg-data:/var/lib/postgresql/data
      
    